"""Performer schema primitives for ArtAgents pipeline stages."""

from .api import PerformerSpec, performer
from .banodoco_catalog import (
    BanodocoCatalogConfig,
    BanodocoCatalogError,
    load_banodoco_catalog_performers,
)
from .folder import (
    FolderPerformerError,
    discover_folder_performer_roots,
    load_folder_performer,
    load_folder_performers,
)
from .install import (
    PerformerInstallError,
    PerformerInstallPlan,
    PerformerInstallResult,
    build_performer_install_plan,
    install_performer,
    performer_environment_path,
    performer_python_path,
)
from .schema import (
    CachePolicy,
    CommandSpec,
    ConditionSpec,
    GraphMetadata,
    IsolationMetadata,
    PerformerDefinition,
    PerformerOutput,
    PerformerPort,
    PerformerValidationError,
    load_performer_manifest,
    validate_performer_definition,
)
from .registry import (
    PerformerRegistry,
    PerformerRegistryError,
    load_builtin_performers,
    load_curated_performers,
    load_default_registry,
)
from .runner import (
    ConditionResult,
    PerformerRunRequest,
    PerformerRunResult,
    PerformerRunnerError,
    build_legacy_context,
    build_performer_command,
    check_performer_binaries,
    evaluate_conditions,
    run_performer,
)

__all__ = [
    "CachePolicy",
    "BanodocoCatalogConfig",
    "BanodocoCatalogError",
    "CommandSpec",
    "ConditionSpec",
    "ConditionResult",
    "FolderPerformerError",
    "GraphMetadata",
    "IsolationMetadata",
    "PerformerDefinition",
    "PerformerOutput",
    "PerformerPort",
    "PerformerInstallError",
    "PerformerInstallPlan",
    "PerformerInstallResult",
    "PerformerRegistry",
    "PerformerRegistryError",
    "PerformerRunRequest",
    "PerformerRunResult",
    "PerformerRunnerError",
    "PerformerSpec",
    "PerformerValidationError",
    "build_legacy_context",
    "build_performer_command",
    "build_performer_install_plan",
    "check_performer_binaries",
    "evaluate_conditions",
    "discover_folder_performer_roots",
    "load_builtin_performers",
    "load_banodoco_catalog_performers",
    "load_curated_performers",
    "load_default_registry",
    "load_folder_performer",
    "load_folder_performers",
    "load_performer_manifest",
    "install_performer",
    "performer_environment_path",
    "performer_python_path",
    "run_performer",
    "performer",
    "validate_performer_definition",
]
