#!/usr/bin/env node
// Renderer parity fixture exporter (T14).
//
// Reads JSON timelines from tests/fixtures/sprint08/ and emits a manifest
// that pairs each timeline with its golden hash file. The intent is to
// snapshot the sprint-08 helpers `createAgentWorkflowTimelineFixture` /
// `createEmbedDemoTimelineFixture` from reigh-app's
// src/tools/video-editor/testing.ts as plain JSON committed under
// tests/fixtures/sprint08/. Once those helpers stabilize the JSON files can
// be regenerated by exporting them via `tsx` and overwriting these fixtures.
//
// Usage:
//   node scripts/node/export_fixtures.mjs            # report present fixtures
//   node scripts/node/export_fixtures.mjs --json     # emit a JSON manifest
//
// This script never writes to the network and never depends on a reigh-app
// checkout being present at any specific path. Missing fixtures are reported
// as empty manifest entries, which is what the Python parity test gates on.

import {readFile, readdir, stat} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const FIXTURES_DIR = path.resolve(REPO_ROOT, 'tests', 'fixtures', 'sprint08');
const GOLDEN_DIR = path.resolve(FIXTURES_DIR, 'golden');

const exists = async (target) => {
  try {
    await stat(target);
    return true;
  } catch {
    return false;
  }
};

const listFixtures = async () => {
  if (!(await exists(FIXTURES_DIR))) {
    return [];
  }
  const entries = await readdir(FIXTURES_DIR, {withFileTypes: true});
  const out = [];
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.json')) {
      continue;
    }
    const fixturePath = path.join(FIXTURES_DIR, entry.name);
    const goldenPath = path.join(GOLDEN_DIR, entry.name.replace(/\.json$/, '.sha256'));
    let goldenHash = null;
    if (await exists(goldenPath)) {
      goldenHash = (await readFile(goldenPath, 'utf8')).trim();
    }
    out.push({
      name: path.basename(entry.name, '.json'),
      fixture_path: fixturePath,
      golden_path: goldenPath,
      golden_hash: goldenHash,
    });
  }
  return out;
};

const main = async () => {
  const fixtures = await listFixtures();
  const manifest = {
    fixtures_dir: FIXTURES_DIR,
    golden_dir: GOLDEN_DIR,
    fixtures,
  };
  if (process.argv.includes('--json')) {
    process.stdout.write(`${JSON.stringify(manifest, null, 2)}\n`);
    return;
  }
  if (fixtures.length === 0) {
    process.stdout.write(
      `No sprint-08 fixtures present at ${FIXTURES_DIR}. ` +
        'Snapshot createAgentWorkflowTimelineFixture / createEmbedDemoTimelineFixture from ' +
        '../reigh-app/src/tools/video-editor/testing.ts and commit the JSON here.\n',
    );
    return;
  }
  for (const fixture of fixtures) {
    process.stdout.write(
      `${fixture.name}\t${fixture.fixture_path}\tgolden=${fixture.golden_hash ?? '(missing)'}\n`,
    );
  }
};

main().catch((error) => {
  process.stderr.write(`export_fixtures: ${error.stack ?? error.message ?? String(error)}\n`);
  process.exit(1);
});
