"""Task-mode kernel APIs."""

from .active_run import clear_active_run, read_active_run, write_active_run
from .env import (
    ARTAGENTS_ACTOR,
    apply_task_run_env,
    child_subprocess_env,
    is_in_task_run,
    task_actor_env,
    task_project_env,
    task_run_id_env,
    task_step_id_env,
)
from .events import (
    append_event,
    canonical_event_json,
    make_nested_entered_event,
    make_nested_exited_event,
    make_run_started_event,
    make_step_attested_event,
    make_step_completed_event,
    make_step_dispatched_event,
    read_events,
    verify_chain,
)
from .gate import (
    AttestedArgs,
    CursorPath,
    GateDecision,
    TaskRunGateError,
    command_for_argv,
    derive_cursor,
    gate_command,
    match_attested_command,
    record_dispatch_complete,
    record_nested_entered,
    record_nested_exited,
    record_step_attested,
)
from .plan import compute_plan_hash, load_plan, step_dir_for

__all__ = [
    "ARTAGENTS_ACTOR",
    "AttestedArgs",
    "CursorPath",
    "GateDecision",
    "TaskRunGateError",
    "append_event",
    "apply_task_run_env",
    "canonical_event_json",
    "child_subprocess_env",
    "clear_active_run",
    "command_for_argv",
    "compute_plan_hash",
    "derive_cursor",
    "gate_command",
    "is_in_task_run",
    "load_plan",
    "make_nested_entered_event",
    "make_nested_exited_event",
    "make_run_started_event",
    "make_step_attested_event",
    "make_step_completed_event",
    "make_step_dispatched_event",
    "match_attested_command",
    "read_active_run",
    "read_events",
    "record_dispatch_complete",
    "record_nested_entered",
    "record_nested_exited",
    "record_step_attested",
    "step_dir_for",
    "task_actor_env",
    "task_project_env",
    "task_run_id_env",
    "task_step_id_env",
    "verify_chain",
    "write_active_run",
]
