"""Task-mode kernel APIs.

Sprint 1 (T9): ``active_run`` re-exports are retired from this package
namespace. The on-disk pointer moved to ``<project>/current_run.json`` +
``runs/<id>/lease.json``; new callers should import
``astrid.core.project.current_run`` and ``astrid.core.session.lease``
directly. A thin backward-compatibility shim still lives at
``astrid.core.task.active_run`` for in-flight callers (it writes the new
on-disk shape).
"""

from .env import (
    ASTRID_ACTOR,
    TASK_ITEM_ID_ENV,
    TASK_ITERATION_ENV,
    TASK_PROJECT_ENV,
    TASK_RUN_ID_ENV,
    TASK_STEP_ID_ENV,
    apply_task_run_env,
    child_subprocess_env,
    is_in_task_run,
    task_actor_env,
    task_item_id_env,
    task_iteration_env,
    task_project_env,
    task_run_id_env,
    task_step_id_env,
)
from .events import (
    append_event,
    canonical_event_json,
    make_cursor_rewind_event,
    make_iteration_failed_event,
    make_nested_entered_event,
    make_nested_exited_event,
    make_run_aborted_event,
    make_run_started_event,
    make_step_attested_event,
    make_step_completed_event,
    make_step_dispatched_event,
    read_events,
    verify_chain,
)
from .inbox import (
    InboxEntry,
    consume_inbox_entry,
    inbox_dir,
    pending_count,
    scan_inbox,
)
from .preamble import PROHIBITION_PREAMBLE
from .gate import (
    AttestedArgs,
    CursorPath,
    GateDecision,
    PeekResult,
    TaskRunGateError,
    command_for_argv,
    derive_cursor,
    gate_command,
    match_attested_command,
    peek_current_step,
    record_dispatch_complete,
    record_nested_entered,
    record_nested_exited,
    record_step_attested,
    validate_attested_identity,
    write_iteration_feedback,
)
from .plan import compute_plan_hash, load_plan, step_dir_for, step_dir_for_path

__all__ = [
    "ASTRID_ACTOR",
    "AttestedArgs",
    "PROHIBITION_PREAMBLE",
    "TASK_ITEM_ID_ENV",
    "TASK_ITERATION_ENV",
    "TASK_PROJECT_ENV",
    "TASK_RUN_ID_ENV",
    "TASK_STEP_ID_ENV",
    "CursorPath",
    "GateDecision",
    "InboxEntry",
    "PeekResult",
    "TaskRunGateError",
    "append_event",
    "apply_task_run_env",
    "canonical_event_json",
    "child_subprocess_env",
    "command_for_argv",
    "compute_plan_hash",
    "consume_inbox_entry",
    "derive_cursor",
    "gate_command",
    "inbox_dir",
    "is_in_task_run",
    "load_plan",
    "make_cursor_rewind_event",
    "make_iteration_failed_event",
    "make_nested_entered_event",
    "make_nested_exited_event",
    "make_run_aborted_event",
    "make_run_started_event",
    "make_step_attested_event",
    "make_step_completed_event",
    "make_step_dispatched_event",
    "match_attested_command",
    "peek_current_step",
    "pending_count",
    "read_events",
    "record_dispatch_complete",
    "record_nested_entered",
    "record_nested_exited",
    "record_step_attested",
    "scan_inbox",
    "step_dir_for",
    "step_dir_for_path",
    "task_actor_env",
    "task_item_id_env",
    "task_iteration_env",
    "task_project_env",
    "task_run_id_env",
    "task_step_id_env",
    "validate_attested_identity",
    "verify_chain",
    "write_iteration_feedback",
]
