#!/usr/bin/env python3
"""Download ai-toolkit training samples + optionally run video_understand, build an HTML collage.

This is a `lora_train` orchestrator step: it runs after training finishes,
between `aitoolkit_train` and `lora_eval_grid` / `human_gate`. Goals:

- scp /workspace/output/<run-name>/samples/ from the pod into the local run dir.
- (optional, --understand) call `astrid.packs.builtin.executors.video_understand.run` on each mp4
  with a custom prompt-alignment query against the training prompt for that column.
- Generate index.html: rows = checkpoint step, cols = training prompts, cells = video +
  prompt text + auto-summary + scores.

The HTML is what the human gate operator looks at when picking a checkpoint.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import subprocess
import sys
import textwrap
from pathlib import Path

STEP_RE = re.compile(r"step[_-]?0*(\d+)", re.IGNORECASE)
PROMPT_RE = re.compile(r"prompt[_-]?(\d+)", re.IGNORECASE)
REPO_ROOT = Path(__file__).resolve().parents[4]

# Query used when --understand is set. Lightweight JSON rubric tailored to LoRA QA.
UNDERSTAND_QUERY_TEMPLATE = textwrap.dedent(
    """\
    This 4-second video is a sample generated by a Seinfeld scene LoRA being trained on
    top of LTX 2.3. The training prompt was: "{prompt}"

    Return compact JSON with:
    - summary: one short sentence describing what is actually in the video
    - prompt_match_score: 0-10 (does the generation match the prompt?)
    - prompt_match_notes: specifically what matches and what doesn't
    - seinfeld_aesthetic: 0-10 (does the look match 90s sitcom Seinfeld?)
    - characters_visible: short list of any recognizable characters (or "none")
    - location_visible: best guess at location depicted (or "unknown")
    - artifacts: any visible glitches, distortion, or anatomy problems
    """
)
UNDERSTAND_RESPONSE_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "summary": {"type": "string"},
        "prompt_match_score": {"type": "number"},
        "prompt_match_notes": {"type": "string"},
        "seinfeld_aesthetic": {"type": "number"},
        "characters_visible": {"type": "string"},
        "location_visible": {"type": "string"},
        "artifacts": {"type": "string"},
    },
    "required": [
        "summary",
        "prompt_match_score",
        "prompt_match_notes",
        "seinfeld_aesthetic",
    ],
}


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser()
    p.add_argument("--pod-handle", type=Path, required=True)
    p.add_argument(
        "--remote-output-dir",
        required=True,
        help="Pod path containing samples/ subdir (e.g. /workspace/output/seinfeld-scene-v1).",
    )
    p.add_argument("--out", type=Path, required=True, help="Local dir to hold downloaded files + HTML.")
    p.add_argument(
        "--staged-config",
        type=Path,
        default=None,
        help="staged_config.yaml path — used to read prompt list for column labels.",
    )
    p.add_argument(
        "--ssh-key",
        default="/tmp/pod_key/id",
        help="Local private key file. Defaults to debug path.",
    )
    p.add_argument(
        "--understand",
        action="store_true",
        help="Run video_understand on each sample to caption + score prompt-alignment.",
    )
    p.add_argument(
        "--understand-mode",
        default="fast",
        choices=["fast", "best"],
        help="video_understand model mode (fast=Flash, best=Pro).",
    )
    p.add_argument("--open", action="store_true", help="Open index.html in a browser when done.")
    p.add_argument("--produces-dir", type=Path, default=None, help="Orchestrator produces dir.")
    return p


def _ssh_target(pod_handle: dict) -> tuple[str, int]:
    ssh = pod_handle["ssh"]
    m = re.match(r"(\S+)\s+-p\s+(\d+)", ssh)
    if not m:
        raise ValueError(f"Unexpected ssh field: {ssh}")
    return m.group(1), int(m.group(2))


def _scp_pull(local_dir: Path, ssh_target: str, port: int, key: str, remote_dir: str) -> None:
    local_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        "scp", "-r",
        "-i", key,
        "-P", str(port),
        "-o", "StrictHostKeyChecking=no",
        "-o", "IdentitiesOnly=yes",
        f"{ssh_target}:{remote_dir}",
        str(local_dir),
    ]
    print(f"$ {' '.join(cmd)}", file=sys.stderr)
    rv = subprocess.run(cmd)
    if rv.returncode != 0:
        raise RuntimeError(f"scp failed rc={rv.returncode}")


def _parse_mp4_name(name: str) -> tuple[int, int | None, str]:
    step_m = STEP_RE.search(name)
    step = int(step_m.group(1)) if step_m else -1
    prompt_m = PROMPT_RE.search(name)
    prompt_idx = int(prompt_m.group(1)) if prompt_m else None
    slug = name.rsplit(".", 1)[0]
    return step, prompt_idx, slug


def _load_prompts(staged_config: Path | None) -> list[str]:
    if not staged_config or not staged_config.is_file():
        return []
    try:
        import yaml
        cfg = yaml.safe_load(staged_config.read_text(encoding="utf-8"))
        return list(cfg["config"]["process"][0]["sample"]["prompts"])
    except Exception as exc:
        print(f"WARN: could not load prompts from {staged_config}: {exc}", file=sys.stderr)
        return []


def _understand_one(mp4: Path, prompt: str, mode: str, out_json: Path) -> dict | None:
    """Call astrid.packs.builtin.executors.video_understand.run on a single mp4."""
    query = UNDERSTAND_QUERY_TEMPLATE.format(prompt=prompt)
    cmd = [
        sys.executable, "-m", "astrid.packs.builtin.executors.video_understand.run",
        "--video", str(mp4),
        "--query", query,
        "--mode", mode,
        "--out", str(out_json),
        "--out-dir", str(out_json.parent / "_vu_windows"),
        "--max-chunks", "1",
        "--chunk-sec", "30",
    ]
    rv = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
    if rv.returncode != 0:
        print(f"WARN: video_understand failed for {mp4.name}: rc={rv.returncode}", file=sys.stderr)
        print(rv.stderr[-500:], file=sys.stderr)
        return None
    if out_json.is_file():
        try:
            data = json.loads(out_json.read_text(encoding="utf-8"))
            # Strip the wrapping schema if video_understand returned its standard envelope.
            if isinstance(data, dict) and "results" in data:
                results = data.get("results") or []
                if results and isinstance(results, list):
                    first = results[0]
                    if isinstance(first, dict) and "response" in first:
                        try:
                            return json.loads(first["response"])
                        except Exception:
                            return first.get("response")
            return data
        except Exception:
            return None
    return None


def _format_understanding(uj: dict | None) -> str:
    if not uj:
        return '<div style="font-size:11px;color:#999">(no understanding)</div>'
    score = uj.get("prompt_match_score")
    aesthetic = uj.get("seinfeld_aesthetic")
    summary = uj.get("summary", "")
    notes = uj.get("prompt_match_notes", "")
    characters = uj.get("characters_visible", "")
    location = uj.get("location_visible", "")
    artifacts = uj.get("artifacts", "")
    parts = [
        f'<div><b>match {score}/10</b> · <b>look {aesthetic}/10</b></div>',
        f'<div style="margin-top:2px">{html.escape(summary)}</div>',
    ]
    if notes:
        parts.append(f'<div style="color:#666;margin-top:2px">notes: {html.escape(notes)}</div>')
    meta = []
    if characters:
        meta.append(f"chars: {html.escape(str(characters))}")
    if location:
        meta.append(f"where: {html.escape(str(location))}")
    if artifacts:
        meta.append(f"artifacts: {html.escape(str(artifacts))}")
    if meta:
        parts.append(f'<div style="color:#888;font-size:10px;margin-top:2px">{" · ".join(meta)}</div>')
    return "".join(parts)


def _build_html(samples_dir: Path, prompts: list[str], understanding: dict[Path, dict | None]) -> str:
    mp4s = sorted(samples_dir.glob("**/*.mp4"))
    if not mp4s:
        return "<html><body><p>No samples found.</p></body></html>"

    by_step: dict[int, list[tuple[int | None, str, Path]]] = {}
    for mp4 in mp4s:
        step, pidx, slug = _parse_mp4_name(mp4.name)
        by_step.setdefault(step, []).append((pidx, slug, mp4))

    steps = sorted(by_step.keys())
    n_cols = max((len(v) for v in by_step.values()), default=1)
    if prompts:
        n_cols = max(n_cols, len(prompts))

    rows_html = []
    for step in steps:
        cells = sorted(by_step[step], key=lambda t: (t[0] if t[0] is not None else 99, t[2]))
        while len(cells) < n_cols:
            cells.append((None, "", None))
        tds = []
        for pidx, slug, path in cells:
            if path is None:
                tds.append("<td>—</td>")
                continue
            rel = path.relative_to(samples_dir.parent)
            uj = understanding.get(path)
            tds.append(
                f'<td>'
                f'<video src="{rel}" controls loop muted preload="metadata" style="width:280px;max-width:100%"></video>'
                f'<div style="font-size:11px;color:#666;margin-top:4px">'
                f'<code>{html.escape(slug)}</code></div>'
                f'{_format_understanding(uj)}'
                f'</td>'
            )
        rows_html.append(
            f'<tr><th style="text-align:right;padding-right:12px;vertical-align:top">'
            f'step<br/><span style="font-size:20px">{step if step >= 0 else "?"}</span></th>'
            + "".join(tds) + "</tr>"
        )

    headers = []
    for c in range(n_cols):
        head = f"prompt {c}"
        if prompts and c < len(prompts):
            head += f"<br/><em style='font-weight:normal;font-size:12px'>{html.escape(prompts[c])}</em>"
        headers.append(f"<th style='vertical-align:top;padding:6px;max-width:300px'>{head}</th>")

    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Seinfeld LoRA — sample collage</title>
<style>
  body {{ font-family:-apple-system,Helvetica,sans-serif; padding:20px; background:#fafafa; }}
  table {{ border-collapse:separate; border-spacing:8px; }}
  th, td {{ vertical-align:top; padding:6px; background:#fff; border-radius:4px;
           box-shadow:0 1px 2px rgba(0,0,0,0.08); }}
  th {{ font-weight:bold; }}
  video {{ display:block; }}
</style>
</head><body>
<h1>Seinfeld scene-LoRA — sample collage</h1>
<p style="color:#666">Rows = checkpoint step. Columns = training prompts (verbatim from staged config).
Each cell shows the generated sample + video_understand auto-caption + prompt-alignment score.
Look for: scene identity, character recognizability, Seinfeld-aesthetic acquisition, over-fit
(generations on novel prompts looking inappropriately Seinfeld-styled).</p>
<table>
<tr><th></th>{''.join(headers)}</tr>
{''.join(rows_html)}
</table>
</body></html>
"""


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    produces = args.produces_dir or args.out
    produces.mkdir(parents=True, exist_ok=True)

    pod_handle = json.loads(args.pod_handle.read_text(encoding="utf-8"))
    target, port = _ssh_target(pod_handle)

    out = args.out
    out.mkdir(parents=True, exist_ok=True)
    samples_local = out / "samples"

    remote = args.remote_output_dir.rstrip("/") + "/samples/."
    try:
        _scp_pull(samples_local, target, port, args.ssh_key, remote)
    except Exception as exc:
        print(f"ERROR: samples download failed: {exc}", file=sys.stderr)
        # Still write an HTML so the orchestrator's downstream step doesn't error on a missing file.
        (out / "index.html").write_text(
            f"<html><body><h1>samples_collage</h1><p>scp failed: {html.escape(str(exc))}</p></body></html>",
            encoding="utf-8",
        )
        return 2

    prompts = _load_prompts(args.staged_config)

    # Pair each mp4 with its prompt (by prompt index in filename) and optionally run video_understand.
    understanding: dict[Path, dict | None] = {}
    if args.understand:
        understand_dir = out / "understand"
        understand_dir.mkdir(parents=True, exist_ok=True)
        mp4s = sorted(samples_local.glob("**/*.mp4"))
        print(f"samples_collage: running video_understand on {len(mp4s)} sample(s)...", file=sys.stderr)
        for mp4 in mp4s:
            step, pidx, slug = _parse_mp4_name(mp4.name)
            prompt_text = prompts[pidx] if (prompts and pidx is not None and pidx < len(prompts)) else ""
            out_json = understand_dir / f"{slug}.json"
            uj = _understand_one(mp4, prompt_text, args.understand_mode, out_json)
            understanding[mp4] = uj

    html_text = _build_html(samples_local, prompts, understanding)
    index_path = out / "index.html"
    index_path.write_text(html_text, encoding="utf-8")
    print(f"samples_collage: wrote {index_path}")

    # Manifest for the orchestrator
    manifest = {
        "status": "ok",
        "samples_dir": str(samples_local),
        "index_html": str(index_path),
        "sample_count": len(list(samples_local.glob("**/*.mp4"))),
        "understood": args.understand,
        "prompts": prompts,
    }
    (produces / "samples_collage_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )

    if args.open:
        subprocess.run(["open", str(index_path)])

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
