#!/usr/bin/env python3
"""Generate Remotion TypeScript types from timeline.py."""

import sys
import types
from pathlib import Path
from typing import Any, Literal, Union, get_args, get_origin, get_type_hints
from typing import is_typeddict as _stdlib_is_typeddict
from typing_extensions import is_typeddict as _ext_is_typeddict


def is_typeddict(value: object) -> bool:
    return _stdlib_is_typeddict(value) or _ext_is_typeddict(value)

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import timeline

BANNER = "// DO NOT EDIT — generated by tools/scripts/gen_remotion_types.py"
DEFAULT_OUTPUT = REPO_ROOT / "remotion" / "src" / "types.generated.ts"
ARRAY_NAMES = [
    "_ASSET_ENTRY_ALLOWED",
    "_CLIP_ALLOWED",
    "_THEME_OVERRIDES_ALLOWED",
    "_TIMELINE_TOP_ALLOWED",
    "_TRACK_ALLOWED",
]


def _is_public_typeddict(name: str, value: object) -> bool:
    return not name.startswith("_") and is_typeddict(value)


def _ordered_typeddicts() -> list[tuple[str, type[Any]]]:
    members = vars(timeline).items()
    public = [(name, value) for name, value in members if _is_public_typeddict(name, value)]
    return sorted(public, key=lambda item: item[0])


def _field_name(interface_name: str, field_name: str) -> str:
    if interface_name == "TimelineClip" and field_name == "from_":
        return "from"
    return field_name


def _render_literal(args: tuple[Any, ...]) -> str:
    parts = [repr(value) if not isinstance(value, str) else f"'{value}'" for value in args]
    return " | ".join(sorted(parts))


def _render_union(args: tuple[Any, ...]) -> str:
    rendered = sorted({_render_type(arg) for arg in args})
    return " | ".join(rendered)


def _render_type(annotation: Any) -> str:
    origin = get_origin(annotation)
    if annotation is Any:
        return "unknown"
    if annotation is str:
        return "string"
    if annotation in (int, float):
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is type(None):
        return "null"
    if origin is Literal:
        return _render_literal(get_args(annotation))
    if origin in (list, list[Any]):
        (item_type,) = get_args(annotation)
        return f"{_render_type(item_type)}[]"
    if origin in (dict, dict[Any, Any]):
        key_type, value_type = get_args(annotation)
        key = "string" if key_type is str else _render_type(key_type)
        value = _render_type(value_type)
        return f"Record<{key}, {value}>"
    if origin in (Union, types.UnionType):
        return _render_union(get_args(annotation))
    if isinstance(annotation, type) and is_typeddict(annotation):
        return annotation.__name__
    if isinstance(annotation, type):
        return annotation.__name__
    return "unknown"


def _render_interface(name: str, typed_dict: type[Any]) -> str:
    hints = get_type_hints(typed_dict, include_extras=True)
    required = set(typed_dict.__required_keys__)
    field_names = sorted(hints)
    lines = [f"export interface {name} {{"]
    for field_name in field_names:
        rendered_name = _field_name(name, field_name)
        optional = "" if field_name in required else "?"
        rendered_type = _render_type(hints[field_name])
        lines.append(f"  {rendered_name}{optional}: {rendered_type};")
    lines.append("}")
    return "\n".join(lines)


def _render_allowed_arrays() -> list[str]:
    rendered = []
    for name in ARRAY_NAMES:
        values = sorted(getattr(timeline, name))
        joined = ", ".join(f"'{value}'" for value in values)
        rendered.append(f"export const {name} = [{joined}] as const;")
    return rendered


def generate() -> str:
    blocks = [BANNER, ""]
    for index, (name, typed_dict) in enumerate(_ordered_typeddicts()):
        if index:
            blocks.append("")
        blocks.append(_render_interface(name, typed_dict))
    blocks.append("")
    blocks.extend(_render_allowed_arrays())
    blocks.append("")
    return "\n".join(blocks)


def main() -> int:
    output_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else DEFAULT_OUTPUT
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
