#!/usr/bin/env python3
"""Generate the capability index block in SKILL.md.

Lists every executor, orchestrator, and element with its short_description so
agents can discover what's available without grepping manifests. Idempotent:
re-running with no manifest changes leaves SKILL.md byte-identical.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from astrid._paths import REPO_ROOT as ARTAGENTS_REPO_ROOT  # noqa: E402
from astrid.core._search import short_description_or_truncated  # noqa: E402
from astrid.core.element.registry import load_default_registry as load_elements  # noqa: E402
from astrid.core.executor.registry import load_default_registry as load_executors  # noqa: E402
from astrid.core.orchestrator.registry import (  # noqa: E402
    load_default_registry as load_orchestrators,
)

SKILL_PATH = REPO_ROOT / "SKILL.md"
BEGIN_MARKER = "<!-- BEGIN CAPABILITY INDEX (auto-generated by scripts/gen_capability_index.py) -->"
END_MARKER = "<!-- END CAPABILITY INDEX -->"


def _row(identifier: str, short: str) -> str:
    cleaned = short.replace("|", "\\|")
    return f"| `{identifier}` | {cleaned} |"


def _section(title: str, items: list[tuple[str, str]]) -> list[str]:
    lines = [f"### {title}", "", "| id | short_description |", "| --- | --- |"]
    if not items:
        lines.append("| _(none)_ | |")
    else:
        for identifier, short in sorted(items, key=lambda pair: pair[0]):
            lines.append(_row(identifier, short or "_(no description)_"))
    lines.append("")
    return lines


def _executor_rows() -> list[tuple[str, str]]:
    registry = load_executors()
    return [
        (executor.id, short_description_or_truncated(executor.short_description, executor.description))
        for executor in registry.list()
    ]


def _orchestrator_rows() -> list[tuple[str, str]]:
    registry = load_orchestrators()
    return [
        (orchestrator.id, short_description_or_truncated(orchestrator.short_description, orchestrator.description))
        for orchestrator in registry.list()
    ]


def _element_rows() -> list[tuple[str, str]]:
    registry = load_elements(active_theme=None, project_root=ARTAGENTS_REPO_ROOT)
    return [
        (
            f"{element.kind}/{element.id}",
            short_description_or_truncated(element.short_description, element.description),
        )
        for element in registry.list()
    ]


def render_block() -> str:
    lines = [BEGIN_MARKER, ""]
    lines.extend(_section("Executors", _executor_rows()))
    lines.extend(_section("Orchestrators", _orchestrator_rows()))
    lines.extend(_section("Elements", _element_rows()))
    lines.append(END_MARKER)
    return "\n".join(lines)


def update_skill(text: str, block: str) -> str:
    if BEGIN_MARKER in text and END_MARKER in text:
        before, _, rest = text.partition(BEGIN_MARKER)
        _, _, after = rest.partition(END_MARKER)
        return f"{before}{block}{after}"
    # Insert before the "## Make something new" heading if present, otherwise
    # append to the end with a leading blank line.
    anchor = "## Make something new"
    if anchor in text:
        before, _, after = text.partition(anchor)
        return f"{before}{block}\n\n{anchor}{after}"
    suffix = "" if text.endswith("\n") else "\n"
    return f"{text}{suffix}\n{block}\n"


def main() -> int:
    block = render_block()
    current = SKILL_PATH.read_text(encoding="utf-8")
    updated = update_skill(current, block)
    if updated != current:
        SKILL_PATH.write_text(updated, encoding="utf-8")
        print(f"updated {SKILL_PATH}")
    else:
        print(f"unchanged {SKILL_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
