#!/usr/bin/env python3
"""Generate the capability index block in SKILL.md.

Lists every executor, orchestrator, and element with its short_description so
agents can discover what's available without grepping manifests. Idempotent:
re-running with no manifest changes leaves SKILL.md byte-identical.

The index is grouped by Sprint 9 pack classification (Core / Bundled
installable / Optional installable / Deprecated). The builtin (Core) section
is further subdivided by per-component classification (primitive,
canonical-demo-internal, candidate-to-extract) sourced from
``docs/git-backed-packs/sprint-09/portfolio.md``.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from astrid._paths import REPO_ROOT as ARTAGENTS_REPO_ROOT  # noqa: E402
from astrid.core._search import short_description_or_truncated  # noqa: E402
from astrid.core.element.registry import load_default_registry as load_elements  # noqa: E402
from astrid.core.executor.registry import load_default_registry as load_executors  # noqa: E402
from astrid.core.orchestrator.registry import (  # noqa: E402
    load_default_registry as load_orchestrators,
)

SKILL_PATH = REPO_ROOT / "SKILL.md"
BEGIN_MARKER = "<!-- BEGIN CAPABILITY INDEX (auto-generated by scripts/gen_capability_index.py) -->"
END_MARKER = "<!-- END CAPABILITY INDEX -->"


# --- Sprint 9 classification ----------------------------------------------
#
# Top-level pack classification. Source of truth:
# docs/git-backed-packs/sprint-09/portfolio.md §2.

PACK_CLASSIFICATION: dict[str, str] = {
    "builtin": "core",
    "iteration": "bundled",
    "upload": "bundled",
    "external": "bundled",
    "seinfeld": "bundled",
}

# Optional-installable third-party-service executors live inside the
# bundled ``external`` pack today but are tracked for a future extraction.
# See docs/git-backed-packs/sprint-09/optional-extraction.md.
OPTIONAL_INSTALLABLE_PREFIXES: tuple[str, ...] = (
    "external.runpod",
    "external.moirae",
    "external.vibecomfy",
    "external.fal_foley",
)

# Per-component classification for the builtin pack. Source of truth:
# docs/git-backed-packs/sprint-09/portfolio.md §3 (per-component table).
BUILTIN_COMPONENT_CLASSIFICATION: dict[str, str] = {
    # primitives
    "builtin.transcribe": "primitive",
    "builtin.scenes": "primitive",
    "builtin.arrange": "primitive",
    "builtin.render": "primitive",
    "builtin.editor_review": "primitive",
    "builtin.asset_cache": "primitive",
    "builtin.generate_image": "primitive",
    "builtin.logo_ideas": "primitive",
    "builtin.vary_grid": "primitive",
    "builtin.iteration_video": "primitive",
    "builtin.video_understand": "primitive",
    "builtin.visual_understand": "primitive",
    "builtin.audio_understand": "primitive",
    "builtin.understand": "primitive",
    "builtin.youtube_audio": "primitive",
    "builtin.inspect_cut": "primitive",
    "builtin.publish": "primitive",
    "builtin.open_in_reigh": "primitive",
    "builtin.reigh_data": "primitive",
    # canonical-demo-internal
    "builtin.shots": "canonical-demo-internal",
    "builtin.quality_zones": "canonical-demo-internal",
    "builtin.triage": "canonical-demo-internal",
    "builtin.scene_describe": "canonical-demo-internal",
    "builtin.quote_scout": "canonical-demo-internal",
    "builtin.pool_build": "canonical-demo-internal",
    "builtin.pool_merge": "canonical-demo-internal",
    "builtin.cut": "canonical-demo-internal",
    "builtin.refine": "canonical-demo-internal",
    "builtin.validate": "canonical-demo-internal",
    "builtin.boundary_candidates": "canonical-demo-internal",
    "builtin.hype": "canonical-demo-internal",
    # candidate-to-extract
    "builtin.animate_image": "candidate-to-extract",
    "builtin.sprite_sheet": "candidate-to-extract",
    "builtin.thumbnail_maker": "candidate-to-extract",
    "builtin.event_talks": "candidate-to-extract",
    "builtin.foley_map": "candidate-to-extract",
    "builtin.foley_review": "candidate-to-extract",
    "builtin.spatial_audio_page": "candidate-to-extract",
    "builtin.tile_video": "candidate-to-extract",
    "builtin.html_canvas_effect": "candidate-to-extract",
    "builtin.human_notes": "candidate-to-extract",
    "builtin.human_review": "candidate-to-extract",
}


def _row(identifier: str, short: str) -> str:
    cleaned = short.replace("|", "\\|")
    return f"| `{identifier}` | {cleaned} |"


def _table(items: list[tuple[str, str]]) -> list[str]:
    lines = ["| id | short_description |", "| --- | --- |"]
    if not items:
        lines.append("| _(none)_ | |")
    else:
        for identifier, short in sorted(items, key=lambda pair: pair[0]):
            lines.append(_row(identifier, short or "_(no description)_"))
    lines.append("")
    return lines


def _executor_rows() -> list[tuple[str, str]]:
    registry = load_executors()
    return [
        (executor.id, short_description_or_truncated(executor.short_description, executor.description))
        for executor in registry.list()
    ]


def _orchestrator_rows() -> list[tuple[str, str]]:
    registry = load_orchestrators()
    return [
        (orchestrator.id, short_description_or_truncated(orchestrator.short_description, orchestrator.description))
        for orchestrator in registry.list()
    ]


def _element_rows() -> list[tuple[str, str]]:
    registry = load_elements(active_theme=None, project_root=ARTAGENTS_REPO_ROOT)
    return [
        (
            f"{element.kind}/{element.id}",
            short_description_or_truncated(element.short_description, element.description),
        )
        for element in registry.list()
    ]


def _pack_id_from_qualified(identifier: str) -> str:
    return identifier.split(".", 1)[0] if "." in identifier else identifier


def _is_optional_installable(identifier: str) -> bool:
    return any(
        identifier == prefix or identifier.startswith(prefix + ".")
        for prefix in OPTIONAL_INSTALLABLE_PREFIXES
    )


def render_block() -> str:
    executor_rows = _executor_rows()
    orchestrator_rows = _orchestrator_rows()
    element_rows = _element_rows()

    # Partition by pack classification.
    core_exec: list[tuple[str, str]] = []
    core_orch: list[tuple[str, str]] = []
    bundled_exec: list[tuple[str, str]] = []
    bundled_orch: list[tuple[str, str]] = []
    optional_exec: list[tuple[str, str]] = []
    optional_orch: list[tuple[str, str]] = []

    def _route(rows: list[tuple[str, str]], core_bucket: list, bundled_bucket: list, optional_bucket: list) -> None:
        for ident, short in rows:
            if _is_optional_installable(ident):
                optional_bucket.append((ident, short))
                continue
            pack = _pack_id_from_qualified(ident)
            cls = PACK_CLASSIFICATION.get(pack, "bundled")
            if cls == "core":
                core_bucket.append((ident, short))
            elif cls == "bundled":
                bundled_bucket.append((ident, short))
            else:
                optional_bucket.append((ident, short))

    _route(executor_rows, core_exec, bundled_exec, optional_exec)
    _route(orchestrator_rows, core_orch, bundled_orch, optional_orch)

    # Sub-partition core (builtin) by per-component classification.
    def _sub_partition(rows: list[tuple[str, str]]) -> dict[str, list[tuple[str, str]]]:
        buckets: dict[str, list[tuple[str, str]]] = {
            "primitive": [],
            "canonical-demo-internal": [],
            "candidate-to-extract": [],
            "unclassified": [],
        }
        for ident, short in rows:
            cls = BUILTIN_COMPONENT_CLASSIFICATION.get(ident, "unclassified")
            buckets[cls].append((ident, short))
        return buckets

    core_exec_sub = _sub_partition(core_exec)
    core_orch_sub = _sub_partition(core_orch)

    lines: list[str] = [BEGIN_MARKER, ""]
    lines.append(
        "Capabilities are grouped by Sprint 9 portfolio classification. "
        "**Core** is always available. **Bundled installable** ships with Astrid "
        "and uses the installable-pack contract. **Optional installable** "
        "components live inside the bundled `external` pack today but depend on "
        "third-party services and are tracked for future extraction. "
        "See `docs/pack-portfolio.md` for the full classification."
    )
    lines.append("")

    # --- Core --------------------------------------------------------------
    lines.append("### Core — `builtin` (always available)")
    lines.append("")
    lines.append(
        "Sub-grouped by per-component classification. **primitive** = reusable "
        "building block end-to-end. **canonical-demo-internal** = called only "
        "from the canonical hype pipeline. **candidate-to-extract** = recorded "
        "for a future extraction sprint, not moved this sprint. See "
        "`docs/git-backed-packs/sprint-09/portfolio.md#per-component-builtin-classification` "
        "for rationales."
    )
    lines.append("")

    def _subsection(title: str, rows: list[tuple[str, str]]) -> list[str]:
        out = [f"##### {title}", ""]
        out.extend(_table(rows))
        return out

    # Executors first, sub-grouped.
    lines.append("#### Executors")
    lines.append("")
    lines.extend(_subsection("primitive", core_exec_sub["primitive"]))
    lines.extend(_subsection("canonical-demo-internal", core_exec_sub["canonical-demo-internal"]))
    lines.extend(_subsection("candidate-to-extract", core_exec_sub["candidate-to-extract"]))
    if core_exec_sub["unclassified"]:
        lines.extend(_subsection("unclassified", core_exec_sub["unclassified"]))

    # Orchestrators.
    lines.append("#### Orchestrators")
    lines.append("")
    lines.extend(_subsection("primitive", core_orch_sub["primitive"]))
    lines.extend(_subsection("canonical-demo-internal", core_orch_sub["canonical-demo-internal"]))
    lines.extend(_subsection("candidate-to-extract", core_orch_sub["candidate-to-extract"]))
    if core_orch_sub["unclassified"]:
        lines.extend(_subsection("unclassified", core_orch_sub["unclassified"]))

    # Elements — always Core today, all ship in `builtin`.
    lines.append("#### Elements")
    lines.append("")
    lines.extend(_table(element_rows))

    # --- Bundled installable ----------------------------------------------
    lines.append("### Bundled installable — `iteration`, `upload`, `external`, `seinfeld`")
    lines.append("")
    lines.append(
        "Ships with Astrid but uses the installable-pack contract end to end "
        "(declared content roots, v1 manifests, subprocess dispatch). "
        "Components from `external/runpod*`, `external/moirae`, "
        "`external/vibecomfy*`, and `external/fal_foley` are split out below "
        "under Optional installable because they depend on third-party services."
    )
    lines.append("")
    lines.append("#### Executors")
    lines.append("")
    lines.extend(_table(bundled_exec))
    lines.append("#### Orchestrators")
    lines.append("")
    lines.extend(_table(bundled_orch))

    # --- Optional installable ---------------------------------------------
    lines.append("### Optional installable — third-party service executors")
    lines.append("")
    lines.append(
        "Currently live inside the bundled `external` pack. Require external "
        "accounts, SDK installs, or running daemons (RunPod, fal.ai, "
        "VibeComfy/ComfyUI, Moirae). Tracked for extraction into separate "
        "installable packs — see "
        "`docs/git-backed-packs/sprint-09/optional-extraction.md`."
    )
    lines.append("")
    lines.append("#### Executors")
    lines.append("")
    lines.extend(_table(optional_exec))
    if optional_orch:
        lines.append("#### Orchestrators")
        lines.append("")
        lines.extend(_table(optional_orch))

    # --- Deprecated --------------------------------------------------------
    lines.append("### Deprecated")
    lines.append("")
    lines.append("_(none in Sprint 9)_")
    lines.append("")

    lines.append(END_MARKER)
    return "\n".join(lines)


def update_skill(text: str, block: str) -> str:
    if BEGIN_MARKER in text and END_MARKER in text:
        before, _, rest = text.partition(BEGIN_MARKER)
        _, _, after = rest.partition(END_MARKER)
        return f"{before}{block}{after}"
    # Insert before the "## Make something new" heading if present, otherwise
    # append to the end with a leading blank line.
    anchor = "## Make something new"
    if anchor in text:
        before, _, after = text.partition(anchor)
        return f"{before}{block}\n\n{anchor}{after}"
    suffix = "" if text.endswith("\n") else "\n"
    return f"{text}{suffix}\n{block}\n"


def main() -> int:
    block = render_block()
    current = SKILL_PATH.read_text(encoding="utf-8")
    updated = update_skill(current, block)
    if updated != current:
        SKILL_PATH.write_text(updated, encoding="utf-8")
        print(f"updated {SKILL_PATH}")
    else:
        print(f"unchanged {SKILL_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
